# Generated by Django 3.1.4 on 2021-08-24 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
