# Generated by Django 3.1.13 on 2021-10-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_submission_indexes_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='errors',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='is_run',
            field=models.BooleanField(default=False),
        ),
    ]
