# Generated by Django 3.1.4 on 2022-12-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20211027_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='indexes_state',
            field=models.TextField(default='[]'),
        ),
    ]
