name: Django CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Pull Docker Image
      run: docker run 0xecho/python3.8.12:latest
    - name: Run Tests
      run: |
        pipenv run python3 manage.py migrate 
        pipenv run python3 manage.py collectstatic
        pipenv run python3 manage.py test
